# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidFinishLaunchingNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('e44dda14156606e26f14b411435c3896_MTc5NDU5MjAxMy0wNS0wOCAxMzo0MzowMi41NDQ3ODk')
  end)
end
